version: "3.7"

services:

  # SERVER
  backend-app:
    build: 
      context: ./SERVER # This specifies the directory where the middleware dockerfile will be running
      dockerfile: Dockerfile
    image: hardarmyyy/apache-middleware-server-01-06
    labels: 
      hardarmyyy/apache-middleware-server-01-06: latest
    container_name: apache-middleware-server
    restart: always
    networks:
      - middleware-network
    env_file: 
      - .env # Ensure to specify the relative path of the env file
    ports:
      - "${PORT}:${PORT}"  # backend-app service container will be exposed to the outside on this port
    environment:
      - "PORT=${PORT}"


  # SERVICE
  httpd:
    build:
      context: ./SERVICE # This specifies the directory where the middleware dockerfile will be running
      dockerfile: Dockerfile
    image: hardarmyyy/apache-middleware-service-01-06
    labels: 
      hardarmyyy/apache-middleware-service-01-06: latest
    container_name: apache-middleware-service
    restart: always
    networks:
      - middleware-network
    env_file: 
      - .env # Ensure to specify the relative path of the env file
    ports:
      - "${SERVICE_PORT}:80"  # httpd service container will be exposed to the outside on this port
    depends_on:
      - backend-app


networks:
  middleware-network:
    driver: bridge

